### ISSUE TITLE
Notification Background Black Color

### ISSUE THREAD

**Issue by furkandvrckrc** [syedmurtaza108/chucker-flutter#100]
![Simulator Screenshot - iPhone 16 Plus - 2024-11-27 at 13 57 45](https://github.com/user-attachments/assets/247f60ca-2d4f-4827-9ccb-6d2c8e4ddb3e)

**Version (please complete the following information):**
Flutter 3.24.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision dec2ee5c1f (2 weeks ago) • 2024-11-13 11:13:06 -0800
Engine • revision a18df97ca5
Tools • Dart 3.5.4 • DevTools 2.37.3
 - OS: iOS
 - Chucker Flutter Version : chucker_flutter 1.8.2

**Comment by furkandvrckrc** [comment]
yes

**Comment by syedmurtaza108** [comment]
The fix for this issue is now live in 1.8.3
