### ISSUE TITLE
http_mock_adapter should be in dev dependency

### ISSUE THREAD

**Issue by quan-ngo-ts** [syedmurtaza108/chucker-flutter#101]
# Describe the issue
The package currently includes http_mock_adapter in the main dependencies. However, this library is only used for unit tests. As such, it should be moved to dev_dependencies instead of dependencies.

# To Reproduce
Steps to reproduce the issue:

Open the project's pubspec.yaml file.
Notice http_mock_adapter is listed under dependencies.
Observe its usage limited to testing purposes.
# Expected behavior
http_mock_adapter should be listed under dev_dependencies in pubspec.yaml, as it is only required for unit testing and not during production or runtime.

# Additional context
Moving http_mock_adapter to dev_dependencies will reduce unnecessary dependencies in the production build. This change aligns with best practices for dependency management in Flutter projects.

**Comment by syedmurtaza108** [comment]
@quan-ngo-ts Thanks for reporting this issue. You are absolutely spot on. I will make it updated in the next planned rlease.

**Comment by syedmurtaza108** [comment]
This change is now live in 1.8.3
