### ISSUE TITLE
Feature Request: UI Layout - More Space for Request List

### ISSUE THREAD

**Issue by quan-ngo-ts** [syedmurtaza108/chucker-flutter#102]
Description:

Love the library! The UI is great, but the request list area is too small, especially with the large success/fail/remaining section and tabs taking up almost half the screen. Could we increase the space for the request list by reducing the size of the other elements? This would improve usability and make it easier to monitor requests.

Suggestions:

Make the success/fail/remaining section smaller.

Reduce the size of the success/failed tabs.

Allocate more vertical space to the request list.

Thanks for considering this!
![image](https://github.com/user-attachments/assets/a9bdef7e-74c5-467f-aed6-7f39a9b5fa5e)

**Comment by syedmurtaza108** [comment]
This enhancement has been done (see https://github.com/syedmurtaza108/chucker-flutter/commit/eaa95c2a514013f8f67c8ed8676a20b74d27570b). It is available in the release 1.8.3.

**Comment by quan-ngo-ts** [comment]
@syedmurtaza108 pls help publish the 1.8.3 to pub.dev, thank you a lot

**Comment by syedmurtaza108** [comment]
@quan-ngo-ts 1.8.3 is already live since about 2 weeks. Is there any issue you are facing with the release??

**Comment by quan-ngo-ts** [comment]
@syedmurtaza108 oh I see it now, thank you
