### ISSUE TITLE
[Mac support] Relying on shared preferences appears to break mac support. 

### ISSUE THREAD

**Issue by neiljaywarner** [syedmurtaza108/chucker-flutter#15]
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

Could you use hive? The docs and pub.dev say supports mac

**Comment by syedmurtaza108** [comment]
@neiljaywarner `SharedPreferences` supports all platforms that Flutter supports. See their [docs](https://pub.dev/packages/shared_preferences). The issue that you are reporting occurs when you are using a package for the first time. I suggest you to uninstall your application completely and then reinstall it.

If this doesn't help you, please visit [Issues](https://github.com/flutter/flutter/issues?q=MissingPluginException+sharedpreferences+getAll) section of Flutter's github. There are already many issues reported similar to above.

By the way I have planned to migrate to `hive` or `moor` but not in near future.

Thank you for using this package🙏.
