### ISSUE TITLE
Flutter GraphQL support?

### ISSUE THREAD

**Issue by santomalau03** [syedmurtaza108/chucker-flutter#16]
Hello dev, is this package already support for flutter_graphql ? 

Thank you

**Comment by syedmurtaza108** [comment]
Not yet @santomalau03

**Comment by santomalau03** [comment]
Thank you dev, is it any chance this package will support to flutter_graphql in the future?

**Comment by syedmurtaza108** [comment]
Yes it will be Insha Allah. 

By the way, it would be great if you can contribute to add graph ql support in your free time🙂
