### ISSUE TITLE
Update dependencies.

### ISSUE THREAD

**Issue by MrUnfunny** [syedmurtaza108/chucker-flutter#24]
**Describe the bug**
This package depends on did 4.0.4 and throws error with dio 5.0.

```
Because every version of chucker_flutter depends on dio ^4.0.4 and app depends on dio ^5.0.0, chucker_flutter is forbidden.
```
This should be fairly simple to fix if there are not any breaking changes in updating dio.

**Comment by syedmurtaza108** [comment]
@MrUnfunny Done and available in the latest release 1.4.3
