### ISSUE TITLE
Add `SafeArea` to request details

### ISSUE THREAD

**Issue by Zazo032** [syedmurtaza108/chucker-flutter#25]
**Describe the bug**
Request detail is not using `SafeArea`, so content is displayed under the navigation bar.

**To Reproduce**
1. Go to a network request details with long content
2. Scroll to the bottom
4. Last item can't be clicked because it's under the navigation bar

**Expected behavior**

**Version (please complete the following information):**
 - Flutter Version: 3.7.8
 - OS: Android/iOS
 - Chucker Flutter Version : 1.4.3

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/2807712/227888420-def07349-aa77-4cfd-83d7-ef320524cc5f.png)
</details>

**Comment by syedmurtaza108** [comment]
Fixed and will be available in the next release
