### ISSUE TITLE
[Request] Add initial settings

### ISSUE THREAD

**Issue by Zazo032** [syedmurtaza108/chucker-flutter#26]
Right now, there's no way to set initial values for any of the settings that the plugin allos (e.g. Notifications enabled/disabled, alignment, duration, http method, api requests thereshold...)

**Comment by syedmurtaza108** [comment]
There is already a settings page to set values to all settings available.

![image](https://github.com/syedmurtaza108/chucker-flutter/assets/44249868/a89ca021-8677-42ff-a042-977fe00d619f)

**Comment by Zazo032** [comment]
> There is already a settings page to set values to all settings available.
> 
> 
> 
> ![image](https://github.com/syedmurtaza108/chucker-flutter/assets/44249868/a89ca021-8677-42ff-a042-977fe00d619f)
> 
> 

You can change all the values there, but the scope of this issue was to add an option in the code to set the default values initially.

**Comment by coyotedev** [comment]
`ChuckerUiHelper.settings = ChuckerUiHelper.settings.copyWith(showNotification: false);`

You can use ChuckerUiHelper like this, it's public class.
