### ISSUE TITLE
Turkish characters in response corrupt

### ISSUE THREAD

**Issue by mustafayilmazdev** [syedmurtaza108/chucker-flutter#28]
**Describe the bug**
There are corruptions in the Turkish characters returned in the response.

**Expected behavior**
{ name_surname= "Mustafa Yılmaz"}
**Screenshots**
![tr_chars](https://user-images.githubusercontent.com/63808749/230566068-ceed8974-17d0-4f9d-885d-80626a90cf26.png)

This is the update request body;
![update_request_body](https://user-images.githubusercontent.com/63808749/230567192-fc9ae853-67ea-4209-8c5a-f29c8ca63086.png)

This is the response from it

![response](https://user-images.githubusercontent.com/63808749/230567446-75abadca-ea0e-461a-a008-cc7266e9d168.png)

**Version**
 - Flutter 3.7.6 • channel stable 
 Dart 2.19.3 
 - OS:  iOS/Android
 - chucker_flutter: ^1.4.3

**Comment by syedmurtaza108** [comment]
Salam @mustafayilmazdev, Thank you for filing this issue. I highly doubt that this issue is related to this package. I think your backend server is not sending these characters properly. Please make sure that server response is proper and let me know if the issue still persists.

**Comment by reddnavneet** [comment]
@mustafayilmazdev Can you check your request/response in postman?
