### ISSUE TITLE
FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by navneet-singh-github** [syedmurtaza108/chucker-flutter#30]
**FormatException: Unexpected character (at character 1)**

I got this error after calling a 404 status code expected API.

**To Reproduce**
1. Call this API https://fakestoreapi.com/productsk using dio

**Expected behavior**
It must show a 404 error in the console not stuck in the interceptor.

**Screenshots**
<img width="929" alt="Screenshot 2023-04-15 at 3 06 52 AM" src="https://user-images.githubusercontent.com/94953723/232159775-c06719b0-fe27-47f0-9175-5c9a9c84c8b9.png">

**Version:**
 - Flutter Version: 3.7.11
 - OS: Android
 - Chucker Flutter Version:  1.5.0

**Comment by syedmurtaza108** [comment]
@navneet-singh-github Thank you for fixing this issue. I have merged your PR and latest changes would be available on [pub.dev](https://pub.dev/packages/chucker_flutter) under 1.5.1.

As a gesture of appreciation, I have added you in README.md 👏.

**Comment by navneet-singh-github** [comment]
Thankyou 😀
