### ISSUE TITLE
intl package version update 

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [syedmurtaza108/chucker-flutter#32]
update the intl package version to 0.18.1

**Comment by syedmurtaza108** [comment]
@Shahmirzali-Huseynov this package doesn't use `intl` package.

**Comment by Shahmirzali-Huseynov** [comment]
I got this error :```
 Because every version of chucker_flutter depends on flutter_localizations from sdk which depends on intl 0.17.0, every version of chucker_flutter requires intl 0.17.0.
So, because ondan depends on both intl ^0.18.1 and chucker_flutter any, version solving failed.
```
