### ISSUE TITLE
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3418 pos 14: 'observer.navigator == null': is not true.

### ISSUE THREAD

**Issue by atharvabhagwat007** [syedmurtaza108/chucker-flutter#46]
**Describe the bug**
I am using auto route and Flutter Chucker navigator observer together. I am getting above issue. Following is my code
part of './main.dart';

class App extends StatelessWidget {
  const App({super.key});

  static final AppRouter appRouter = AppRouter(
    authenticationRouteGuard: AuthenticationRouteGuard(),
  );

  // This widget is the root of your application.
  @override
  Widget build(final BuildContext context) => MaterialApp.router(
        title: 'title',
        debugShowCheckedModeBanner: false,
        routerDelegate: appRouter.delegate(
          navigatorObservers: () => [
            ChuckerFlutter.navigatorObserver,
            MyObserver(),
            AutoRouteObserver(),
          ],
        ),
        routeInformationParser: appRouter.defaultRouteParser(),
        builder: (
          final BuildContext context,
          final Widget? widget,
        ) =>
            StreamChat(
          client: (Injector.resolve<ChatClient>() as ChatClient).client,
          child: widget,
        ),
      );
}

**Comment by arthuravilacompass** [comment]
Got any update on this? I have a similar issue with GoRouter

**Comment by shubhanus** [comment]
any update or workaround on this?

**Comment by ivangalkindeveloper** [comment]
Solution - you must add the navigator observer to your router config
Example for auto_route:
```dart
router.config(
        navigatorObservers: () => [
          ChuckerFlutter.navigatorObserver,
        ],
      );
```
