### ISSUE TITLE
chucker pop up shows multiple times on one endpoint hit

### ISSUE THREAD

**Issue by RakaAlrian** [syedmurtaza108/chucker-flutter#66]
**Describe the bug**
Chucker pop up shows multiple times on one endpoint hit after upgrading to version 1.6.3

**To Reproduce**
1. Upgrade flutter 3.7.0 to 3.10.0
2. Upgrade chucker 1.6.0 to 1.6.3

**Expected behavior**
Show only one pop up on one endpoint hit

**Version (please complete the following information):**
 - Flutter Version: 3.10.0
 - OS: Android
 - Chucker Flutter Version : 1.6.3

**Comment by syedmurtaza108** [comment]
@RakaAlrian Looks this is no longer a valid issue. Thank you for the update.
