### ISSUE TITLE
[Request] feature request: copy http request "as curl"

### ISSUE THREAD

**Issue by SyifaAinnur** [syedmurtaza108/chucker-flutter#86]
I think it is necessary to add additional features to share as curl, this I think will help when sending to the backend or testers

![image](https://github.com/user-attachments/assets/9f714c8c-1fba-4911-8b82-f7317c9c3871)

**Comment by syedmurtaza108** [comment]
@SyifaAinnur Thanks for filing this request. I believe this is a great idea. It would be great if you can start on this feature yourself as I am very much busy these days.
If you too aren't available I will take on this whenever have some free time.

**Comment by SyifaAinnur** [comment]
@syedmurtaza108 , I have made a pull request for this feature, you can check the additions and changes, big thanks
